name: Publish
run-name: Publish

on:
    workflow_run:
        workflows:
            - Build
        types:
            - completed

jobs:
    tag:
        name: Tag Version
        needs: build
        runs-on: ubuntu-latest
        container: node
        steps:
            -   name: Clone Repository
                uses: ztimson/actions/clone@develop

            -   name: Get Version Number
                run: echo "VERSION=$(cat package.json | grep version | grep -Eo ':.+' | grep -Eo '[[:alnum:]\.\/\-]+')" >> $GITHUB_ENV

            -   name: Tag Version
                uses: ztimson/actions/tag@develop
                with:
                    tag: ${{env.VERSION}}
